### ISSUE TITLE
Fill command fails to run properly

### ISSUE THREAD

**Issue by mvy** [prologin/concours-site#12]
> ###### Originally posted 2015-06-30 07:52 by [mvy](https://bitbucket.org/mvy/) on Bitbucket

The `python manage.py fill_db all` fails in sponsors module due to a problem with the email format.

```
#!bash

Loading data for module sponsors...
(0.000) QUERY = 'BEGIN' - PARAMS = (); args=None
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mvyonline/git/prologin/site/site-env/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/mvyonline/git/prologin/site/site-env/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mvyonline/git/prologin/site/site-env/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/mvyonline/git/prologin/site/site-env/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/mvyonline/git/prologin/site/prologin/prologin/management/commands/fill_db.py", line 359, in handle
    method()
  File "/home/mvyonline/git/prologin/site/prologin/prologin/management/commands/fill_db.py", line 182, in fill_sponsors
    email="contact@%s.fr" % slug).save()
  File "/home/mvyonline/git/prologin/site/site-env/lib/python3.4/site-packages/django/db/models/base.py", line 452, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'email' is an invalid keyword argument for this function

```

**Comment by zopieux** [comment]
> ###### Originally posted 2015-06-30 16:22 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fix fill_db sponsors field name, should fix #12


→ <<cset a25b0d3ff2ac>>
