### ISSUE TITLE
semifinals: server not booting due to djmail import error

### ISSUE THREAD

**Issue by lportemo** [prologin/concours-site#312]
```
déc. 30 18:00:38 semifinals gunicorn[10620]: RuntimeError: Model class djmail.models.Message doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
déc. 30 18:00:38 semifinals gunicorn[10620]: During handling of the above exception, another exception occurred:
déc. 30 18:00:38 semifinals gunicorn[10620]: Traceback (most recent call last):
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
déc. 30 18:00:38 semifinals gunicorn[10620]:     self.handle_request(listener, req, client, addr)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
déc. 30 18:00:38 semifinals gunicorn[10620]:     respiter = self.wsgi(environ, resp.start_response)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
déc. 30 18:00:38 semifinals gunicorn[10620]:     response = self.get_response(request)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
déc. 30 18:00:38 semifinals gunicorn[10620]:     response = self._middleware_chain(request)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
déc. 30 18:00:38 semifinals gunicorn[10620]:     response = response_for_exception(request, exc)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 95, in response_for_exception
déc. 30 18:00:38 semifinals gunicorn[10620]:     exc_info=sys.exc_info(),
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/utils/log.py", line 228, in log_response
déc. 30 18:00:38 semifinals gunicorn[10620]:     exc_info=exc_info,
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
déc. 30 18:00:38 semifinals gunicorn[10620]:     self._log(ERROR, msg, args, **kwargs)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
déc. 30 18:00:38 semifinals gunicorn[10620]:     self.handle(record)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
déc. 30 18:00:38 semifinals gunicorn[10620]:     self.callHandlers(record)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
déc. 30 18:00:38 semifinals gunicorn[10620]:     hdlr.handle(record)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
déc. 30 18:00:38 semifinals gunicorn[10620]:     self.emit(record)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/utils/log.py", line 122, in emit
déc. 30 18:00:38 semifinals gunicorn[10620]:     self.send_mail(subject, message, fail_silently=True, html_message=html_message)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/utils/log.py", line 125, in send_mail
déc. 30 18:00:38 semifinals gunicorn[10620]:     mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/utils/log.py", line 128, in connection
déc. 30 18:00:38 semifinals gunicorn[10620]:     return get_connection(backend=self.email_backend, fail_silently=True)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/core/mail/__init__.py", line 34, in get_connection
déc. 30 18:00:38 semifinals gunicorn[10620]:     klass = import_string(backend or settings.EMAIL_BACKEND)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
déc. 30 18:00:38 semifinals gunicorn[10620]:     module = import_module(module_path)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
déc. 30 18:00:38 semifinals gunicorn[10620]:     return _bootstrap._gcd_import(name[level:], package, level)
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/djmail/backends/default.py", line 6, in <module>
déc. 30 18:00:38 semifinals gunicorn[10620]:     from .. import core
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/djmail/core.py", line 11, in <module>
déc. 30 18:00:38 semifinals gunicorn[10620]:     from .models import Message
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/djmail/models.py", line 6, in <module>
déc. 30 18:00:38 semifinals gunicorn[10620]:     class Message(models.Model):
déc. 30 18:00:38 semifinals gunicorn[10620]:   File "/home/prologin/site/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 111, in __new__
déc. 30 18:00:38 semifinals gunicorn[10620]:     "INSTALLED_APPS." % (module, name)
```

I found 2 workarounds to solve this problem :

* add the following line to django semifinals config :

```python
del(EMAIL_BACKEND)
```

* or add `djmail` to `INSTALLED_APPS`

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/312
